name: Goblin Chaos Populator 🐲🔥
description: Let our goblins populate your repository with chaotic issues, PRs, commits, releases, and more!
inputs:
  num_issues:
    description: "Number of issues to create"
    required: false
    default: 5
  num_prs:
    description: "Number of pull requests to create"
    required: false
    default: 5
  num_commits:
    description: "Number of commits to create"
    required: false
    default: 5
  num_releases:
    description: "Number of releases to create"
    required: false
    default: 2
  num_files:
    description: "Number of files to upload per branch"
    required: false
    default: 3
branding:
  icon: "zap"  # for chaotic energy
  color: "green"  # Mischievous goblin-like color
