name: Goblin Chaos Populator 🐲🔥
description: Populate your repository with chaotic goblin issues, PRs, commits, releases, and more!
author: melscoop
inputs:
  num_issues:
    description: "Number of issues to create"
    required: false
    default: 5
  num_prs:
    description: "Number of pull requests to create"
    required: false
    default: 5
  num_commits:
    description: "Number of commits to create"
    required: false
    default: 5
  num_releases:
    description: "Number of releases to create"
    required: false
    default: 2
  num_files:
    description: "Number of files to upload per branch"
    required: false
    default: 3
runs:
  using: "composite"
  steps:
    - name: Run Python Script
      shell: bash
      run: |
        python3 goblin_populator.py
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        
permissions:
  contents: write
  issues: write
  pull-requests: write
  metadata: read
